# Generated by Django 6.0.1 on 2026-02-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_iplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplog',
            name='ip_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iplog',
            name='ip_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iplog',
            name='ip_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
